server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never

spring:
  application:
    name: money
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:postgresql://localhost:5432/teste_e2e
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    tomcat:
      maxActive: 50
      maxIdle: 50
      minIdle: 1
      initialSize: 1
  jpa:
    properties:
      hibernate:
        query:
          plan_cache_max_size: 1024
          plan_parameter_metadata_max_size: 64
          in_clause_parameter_padding: true
        jdbc:
          lob.non_contextual_creation: true
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
